package blocks

// builtinSchemas maps block_type → Draft-07-style object-schema JSON for the
// block's config. Keep in sync with builtinInfo and DefaultRegistry.
var builtinSchemas = map[string]string{
	TypeAstarteSource:     `{"type":"object","properties":{"realm":{"type":"string","description":"Astarte realm (default deps.Realm)"},"interface":{"type":"string","description":"Astarte interface to subscribe to"},"path":{"type":"string","description":"Path prefix filter for emitted messages"}},"required":[]}`,
	TypeFilter:            `{"type":"object","properties":{"key_prefix":{"type":"string","description":"Drop unless key starts with this prefix"},"key_contains":{"type":"string","description":"Drop unless key contains this substring"},"type":{"type":"string","description":"Payload type filter; one of integer|real|boolean|datetime|binary|string|map"},"metadata":{"type":"object","description":"Exact-match metadata string→string"}},"required":[]}`,
	TypeMap:               `{"type":"object","properties":{"key":{"type":"string","description":"Key template with {key} and {metadata.<name>} placeholders"},"set_metadata":{"type":"object","description":"Metadata string→string merged into messages"},"delete_metadata":{"type":"array","description":"Metadata keys to delete"}},"required":[]}`,
	TypeToJSON:            `{"type":"object","properties":{}}`,
	TypeUpdateMetadata:    `{"type":"object","properties":{"set_metadata":{"type":"object","description":"Metadata string→string to merge; at least one of set_metadata, delete_metadata is required"},"delete_metadata":{"type":"array","description":"Metadata keys to delete; at least one of set_metadata, delete_metadata is required"}},"required":[]}`,
	TypeSplitMap:          `{"type":"object","properties":{"key_template":{"type":"string","description":"Output key template with {key} and {field} placeholders (default \"{key}/{field}\")"}},"required":[]}`,
	TypeRandomSource:      `{"type":"object","properties":{"type":{"type":"string","description":"Value type to emit; one of integer|real|boolean"},"interval_ms":{"type":"integer","description":"Milliseconds between emissions (default 1000)"},"min":{"type":"number","description":"Minimum value (inclusive)"},"max":{"type":"number","description":"Maximum value (inclusive)"},"key":{"type":"string","description":"Message key (default \"random\")"}},"required":["type"]}`,
	TypeSort:              `{"type":"object","properties":{"window_ms":{"type":"integer","description":"Buffering window in milliseconds (default 1000, must be ≥ 0)"},"dedup":{"type":"boolean","description":"Release each key once per window (default false)"}},"required":[]}`,
	TypeJSONPathMap:       `{"type":"object","properties":{"template":{"type":"string","description":"Template with $MESSAGE and $METADATA.<name> placeholders; unresolvable paths fail the message"}},"required":["template"]}`,
	TypeHTTPSource:        `{"type":"object","properties":{"urls":{"type":"array","description":"URLs to poll GET round-robin (at least one)"},"interval_ms":{"type":"integer","description":"Milliseconds between polls (default 1000)"},"timeout_ms":{"type":"integer","description":"Per-request timeout in milliseconds (default 5000)"}},"required":["urls"]}`,
	TypeHTTPSink:          `{"type":"object","properties":{"url":{"type":"string","description":"Base URL to POST payloads to"},"method":{"type":"string","description":"HTTP method (default \"POST\")"},"timeout_ms":{"type":"integer","description":"Per-request timeout in milliseconds (default 5000)"},"headers":{"type":"object","description":"Extra request headers string→string"}},"required":["url"]}`,
	TypeMQTTSource:        `{"type":"object","properties":{"url":{"type":"string","description":"Broker URL (e.g. tcp://127.0.0.1:1883)"},"topics":{"type":"array","description":"Topics to subscribe to (at least one, non-empty strings)"},"qos":{"type":"integer","description":"Subscription QoS level 0|1|2 (default 0)"},"client_id":{"type":"string","description":"Optional MQTT client ID (random when unset)"},"username":{"type":"string","description":"Optional username"},"password":{"type":"string","description":"Optional password"}},"required":["url","topics"]}`,
	TypeMQTTSink:          `{"type":"object","properties":{"url":{"type":"string","description":"Broker URL (e.g. tcp://127.0.0.1:1883)"},"topic":{"type":"string","description":"Topic to publish to"},"qos":{"type":"integer","description":"Publish QoS level 0|1|2 (default 0)"},"retained":{"type":"boolean","description":"Set the retain flag on published messages (default false)"},"client_id":{"type":"string","description":"Optional MQTT client ID (random when unset)"},"username":{"type":"string","description":"Optional username"},"password":{"type":"string","description":"Optional password"}},"required":["url","topic"]}`,
	TypeContainer:         `{"type":"object","properties":{"image":{"type":"string","description":"Docker image run as a transform"},"config":{"type":"object","description":"Object passed to the container as ASTRATE_FLOW_CONFIG"},"port":{"type":"integer","description":"Container HTTP bridge port (default 8080)"},"timeout_ms":{"type":"integer","description":"Per-message POST timeout in milliseconds (default 5000)"},"ready_timeout_ms":{"type":"integer","description":"Health-check wait in milliseconds (default 15000)"}},"required":["image"]}`,
	TypeVirtualDevicePool: `{"type":"object","properties":{"devices":{"type":"array","items":{"type":"string"},"minItems":1,"description":"Registered device_ids this pool may publish as"}},"required":["devices"]}`,
	TypeNullSink:          `{"type":"object","properties":{}}`,
	TypeLogSink:           `{"type":"object","properties":{}}`,
}
